#!/usr/bin/env bash

if [ $1 = "s" ] || [ $1 = "status" ]; then
    protonvpn-cli s
elif [ $1 = "d" ] || [ $1 = "disconnect" ]; then
    protonvpn-cli d
elif [ $1 = "c" ] || [ $1 = "connect"  ]; then
    protonvpn-cli c $2
fi


