#!/usr/bin/env bash

test="No active Proton VPN connection."

status=$(echo $(protonvpn-cli s))

if [[ "$status" == "$test" ]]; then
    echo "Not connected."
    protonvpn-cli c FR#10
else
    if [[ "$status" == *FR#10* ]]; then
        echo "Already connected to FR#10"
    else
        echo "Already connected to different server."
        protonvpn-cli d
        protonvpn-cli c FR#10
    fi
fi

protonvpn-cli s
