#!/usr/bin/env bash

default_server=FR#27
test="No active Proton VPN connection."

vpn_status=$(echo $(protonvpn-cli s))

if [[ $# -eq 1 ]]; then
    default_server=$1
else
    echo "No server provided. Default server: $default_server"
fi

if [[ "$vpn_status" == "$test" ]]; then
    echo "Not connected."
    protonvpn-cli c $default_server
else
    connection_status=$(protonvpn-cli s | grep "Server:" | awk '{print $2}')
    if [[ $connection_status == $default_server ]]; then
        echo "Already connected to $default_server."
    else
        echo "Already connected to $connection_status."
        protonvpn-cli d
        protonvpn-cli c FR#27
    fi
fi

protonvpn-cli s
